POST http://srv77343.seohost.com.pl/newUser HTTP/1.1
Content-Type: application/json

{
    "userName": "Sara",
    "password": "1234",
    "email": "sar2a@gmail.com",
    "firstName": "Joel",
    "lastName": "Gonzalez"
}

POST http://localhost:3000/beeVice HTTP/1.1
Content-Type: application/json

{
    "ownerId": "1",
    "serialNumber": "1234"
}

POST http://localhost:3000/sensorReads HTTP/1.1
Content-Type: application/json

{
    "beeViceId": "1",
    "sensorType": "1",
    "value": "29.5"
}

POST srv77343.seohost.com.pl/beeViceLogs HTTP/1.1
Content-Type: application/json

{
    "beeViceId": "1",
    "batteryLevel": "60.2",
    "additionalMessage": "Test__ BeeVice is online"
}

GET srv77343.seohost.com.pl/sensorTypes HTTP/1.1



POST srv77343.seohost.com.pl/beeViceLogs HTTP/1.1
Content-Type: application/json

{
    "beeViceId": "1",
    "batteryLevel": "60.2",
    "additionalMessage": "Test__ BeeVice is online"
}

GET srv77343.seohost.com.pl/hives/1/sensorReads HTTP/1.1
Content-Type: application/json

POST srv77343.seohost.com.pl/beeHives HTTP/1.1
Content-Type: application/json

{
    "ownerId": "1",
    "beeViceId": "1",
    "queenColor": "white",
    "breed": "Italian"
}

POST srv77343.seohost.com.pl/beeHives HTTP/1.1
Content-Type: application/json

{
    "ownerId": "1",
    "queenColor": "red",
    "breed": "Italian"
}

POST http://srv77343.seohost.com.pl/login HTTP/1.1
Content-Type: application/json

{
    "password": "1234",
    "email": "sara@gmail.com"
}

POST http://srv77343.seohost.com.pl/newCommand HTTP/1.1
Content-Type: application/json

{
    "beeViceId": "1",
    "commandId": "1",
    "params": {
        "ssid": "myWifi",
        "password": "myPassword"
    }
}

PUT http://srv77343.seohost.com.pl/queuedCommands/1/executed HTTP/1.1
Content-Type: application/json

GET http://srv77343.seohost.com.pl/hives/1/sensorReads?startDate=2025-01-21%2000:00:00&endDate=2025-01-31%2023:59:59 HTTP/1.1

POST http://srv77343.seohost.com.pl/inspections HTTP/1.1
Content-Type: application/json

{
    "hiveId": "1",
    "inspectionDate": "2025-01-21",
    "inspectionType": "1",
    "additionalMessage": "Test__ BeeHive is healthy"
}